[package]
name = "papyrus"
version = "0.1.0"
authors = ["J.M. Thiessen <jacob@x0rz3q.com>"]
edition = "2018"

[dependencies]
rand = "0.7"
clap = "2.33.0"
log = "0.4.8"
env_logger = "0.6.2"
threadpool = "1.7.1"
users = "0.9"

[profile.release]
opt-level = 3
